[profile.default]
src = "src"
out = "out"
libs = ["lib"]
rpc_endpoints = {sepolia-eth ="https://eth-sepolia.g.alchemy.com/v2/y7HbpS-bDScWAoBcc6yfzfE9thM6AavW", arb-sepolia ="https://arb-sepolia.g.alchemy.com/v2/ROIuM8uFXLe3846n3aDqw"}
remappings = [
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
    "@ccip=lib/ccip/contracts",
    "@chainlink/local/=lib/chainlink-local/"
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
